Iteam1337/predictivemovement

.vscode/settings.json, k8s/README.md, k8s/aws-ebs-driver.yaml, k8s/gp2-storageclass.yaml, k8s/io1-storageclass.yaml, k8s/k8s-cluster.md, k8s/match-route.yaml, k8s/osrm.yaml, k8s/redis.yaml, k8s/traefik.yaml, packages/match-route/Dockerfile, packages/match-route/lib/adapters/redis.js, packages/match-route/lib/config.js
Init kubernetes and read redis variables from config
=> feat: ci cd

.travis.yml
more code duplication for building and deploying plot-routes since lerna
is not an option currently without making actual tag releases to
determine which packages have changed
=> chore: 🤖 include plot-routes in the travis config

packages/booking-interface/consumers/deliveryConfirmed.js, packages/booking-interface/consumers/pickupConfirmed.js, packages/driver-interface/botRoutes.js, packages/driver-interface/consumers/pickupOffers.js, packages/driver-interface/services/cache.js, packages/driver-interface/services/messaging.js, packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/routes.js, packages/engine-ui/package-lock.json, packages/engine-ui/src/App.js, packages/engine-ui/src/utils/reducer.js
Remove booking from map
Introduce simple cache to handle booking state in drivers interface
=> feat: remove booking from map

packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/routes.js, packages/engine-server/package-lock.json, packages/engine-server/package.json, packages/engine-ui/src/App.js, packages/engine-ui/src/components/Sidebar.js
Co-authored-by: Andreas Lundqvist <momentiris@gmail.com>
=> feat: create booking from UI

packages/engine-ui/src/App.js, packages/engine/lib/booking.ex, packages/engine/lib/booking_processor.ex, packages/engine/lib/candidates.ex, packages/engine/lib/match_producer.ex, packages/engine/lib/vehicle.ex
- booking as a genserver and has its own state
- fix issue with UI breaking on accept offer
=> feat: booking as genserver

packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/routes.js, packages/engine-ui/src/components/Map.js, packages/engine-ui/src/utils/mapUtils.js, packages/engine/lib/vehicle.ex
- engine publishes newly created vehicles to vehicles exchange with key `new` (anyone interested should use this information to be in parity with the engine)
- made the engine-server use the vehicles exchange to get the vehicles information and send it to the ui
=> refactor: plot vehicle activities

packages/engine-ui/src/components/CreateBooking.js, packages/engine-ui/src/components/Sidebar.js
- add secondary sidebar
- remove layers from url in search results
=> chore: small ui fixes

packages/message_generator/test/message_generator_test.exs, packages/route-optimization-jsprit/src/main/java/com/predictivemovement/route/optimization/VRPSetting.java, packages/route-optimization-jsprit/src/main/java/com/predictivemovement/route/optimization/VRPSettingTimeWindows.java, packages/route-optimization-jsprit/src/test/java/com/predictivemovement/route/optimization/VRPSettingTimeWindowsTest.java, packages/route-optimization-jsprit/src/test/resources/route_request_04.json
- earliest and latest values for time_windows are passed in ISO format
- calculate the diff between now and earliest/latest in jsprit
=> chore: calculate time diff in jsprit

packages/engine-ui/src/assets/vehicle.svg, packages/engine-ui/src/components/Map.js, packages/engine-ui/src/utils/mapUtils.js
- Change icon for vehicle 
- Add icon for booking
=> chore: ui map

packages/engine-ui/package-lock.json, packages/engine-ui/package.json, packages/engine-ui/src/components/forms/inputs/AddressSearchInput.js, packages/engine-ui/src/utils/hooks.js
=> chore: include county in search result

packages/elixir_umbrella/elixir_apps/engine/lib/booking.ex, packages/elixir_umbrella/elixir_apps/engine/lib/booking_delete_processor.ex, packages/elixir_umbrella/elixir_apps/engine/lib/booking_store.ex, packages/elixir_umbrella/elixir_apps/engine/lib/engine/application.ex, packages/elixir_umbrella/elixir_apps/engine/lib/redis_adapter.ex, packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/routes.js, packages/engine-ui/src/App.js, packages/engine-ui/src/components/BookingDetails.js, packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/Sidebar.js, packages/engine-ui/src/shared-elements/buttons.ts, packages/engine-ui/src/utils/reducer.js
remove it from store, remove the process, recalculate plan
=> feat: 🎸 delete booking

packages/engine-ui/src/components/CreateVehicle.js, packages/engine-ui/src/components/Transports.tsx, packages/engine-ui/src/components/forms/CreateBooking.js, packages/engine-ui/src/components/forms/CreateVehicle.js, packages/engine-ui/src/components/forms/inputs/AddressSearchInput.js, packages/engine-ui/src/components/forms/inputs/Checkbox.tsx, packages/engine-ui/src/shared-elements/form.ts
Move parcel details to bottom and make user toggle it, hiding it on default.
Add red asterisk to required fields.
=> chore: toggle parcel details and input reorder

packages/elixir_umbrella/elixir_apps/engine/lib/dispatcher.ex, packages/elixir_umbrella/elixir_apps/engine/lib/match_producer.ex, packages/elixir_umbrella/elixir_apps/engine/lib/vehicle.ex, packages/elixir_umbrella/elixir_apps/engine/test/booking_updates_processor_test.exs
This refactor the make function of Vehicle and also inserts capacity as a default value.
=> chore: add default capacity & refactor vehiclemake

packages/engine-ui/src/components/BookingDetails.js
On booking details page, "Bokad transport" showed booking id. Should show transport id
=> chore: write out vehicle id rather than booking id on details page

docker-compose.yml, packages/driver-interface/adapters/amqp.js, packages/driver-interface/consumers/pickupInstructions.js, packages/driver-interface/consumers/vehiclePlan.js, packages/elixir_umbrella/elixir_apps/engine/lib/vehicle.ex, packages/engine-server/lib/engineConnector.js
Update some queue names to be like they are in https://app.mural.co/t/iteam8347/m/iteam8347/1580473852797/a46b29006a858db8d209144082469a5158a6f440
=> chore: change queue names

packages/engine-ui/package-lock.json, packages/engine-ui/package.json
=> chore: cleanup

packages/driver-interface/consumers/pickupInstructions.js, packages/driver-interface/consumers/vehiclePlan.js, packages/driver-interface/services/messaging.js, packages/engine-ui/src/components/BookingDetails.js, packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/Plan.tsx, packages/engine-ui/src/components/PlanRouteDetails.tsx, packages/engine-ui/src/components/RouteActivities.js, packages/engine-ui/src/components/VehicleDetails.tsx, packages/engine-ui/src/components/Vehicles.tsx, packages/engine-ui/src/shared-elements/layout.ts, packages/engine-ui/src/shared-elements/typography.ts, packages/engine-ui/src/utils/helpers.ts
Shortens ID:s displayed in the admin UI and in the client interface (driver bot)
=> feat: shorten ids

packages/engine-ui/src/components/forms/CreateBooking.js
Adds regex to validate input on the "measurements" and "contact" inputs when creating a booking.
=> chore: validate form fields

packages/driver-interface/README.md, packages/driver-interface/adapters/redis.js, packages/driver-interface/botRoutes.js, packages/driver-interface/consumers/pickupInstructions.js, packages/driver-interface/consumers/vehiclePlan.js, packages/driver-interface/package-lock.json, packages/driver-interface/package.json, packages/driver-interface/services/bot.js, packages/driver-interface/services/cache.js
Use redis for caching in driver interface
=> feat(driver-interface): use redis for cache

packages/engine-ui/src/components/Notifications.tsx, packages/engine-ui/src/types.ts
Notifications was showing when confirming a plan. This might be something we want in the future but for now it showed the wrong message.
=> fix: notifications

packages/engine-server/lib/routes.js, packages/engine-ui/src/App.js
Was checking if end destination was set, but we send in end position
=> fix: show end address

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/Notifications.tsx
State should persist on /bookings when going from and to /bookings <--> /bookings/:id
=> feat: persist state bookings

packages/engine-ui/src/components/Sidebar.tsx
Now we redirect the user from the root to `/bookings`
=> chore: redirect from "/" to "/bookings"

packages/engine-ui/src/components/Sidebar.tsx, packages/engine-ui/src/components/VehicleDetails.tsx, packages/engine-ui/src/shared-elements/buttons.ts
Change style for delete button
=> chore: delete button

packages/engine-ui/src/components/Map.js, packages/engine-ui/src/utils/mapUtils.js
- Line is rounded 
- Thicker route line
- Parcel icon to front 
- Bigger parcel icon
=> feat: rounded map line

packages/engine-ui/src/components/BookingDetails.js, packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/Map.js, packages/engine-ui/src/components/VehicleDetails.tsx, packages/engine-ui/src/components/Vehicles.tsx, packages/engine-ui/src/utils/UIStateContext.js, packages/engine-ui/src/utils/hooks.js
Don't show bookings when on /transports, and vice verca. Also fixing highlighting so it's working properly.
=> feat(engine-ui): filter state on various routes

packages/engine_umbrella/apps/engine/lib/processors/booking_processor.ex, packages/engine_umbrella/config/config.exs, packages/engine_umbrella/config/releases.exs
use broadway batching inside booking processor
=> feat: 🎸 booking processor batcher

packages/engine-ui/src/components/forms/CreateVehicle.js, packages/engine-ui/src/components/forms/inputs/DateInput.tsx, packages/engine-ui/src/components/forms/inputs/TimeRestriction.js
https://trello.com/c/YBx7yg08/256-remove-minimum-time-restrictions-when-adding-a-new-transport
=> fix: update fields

packages/engine_umbrella/apps/engine/lib/engine/application.ex
Let the stores be created first to not allow any race condition
=> chore(engine): change application startup order

packages/engine-ui/src/components/forms/CreateBooking.js
Fixed clearer instructions for the format for the measurement validation.
=> chore: add the expected format when validating

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/Transports.tsx, packages/engine-ui/src/shared-elements/buttons.ts, packages/engine-ui/src/shared-elements/layout.ts
Changed layout for the "+ Lägg till bokning" and "+ Lägg till transport" to make the buttons more visible
=> improvement: change add booking/transport cta

packages/driver-interface/src/consumers/pickupInstructions.ts, packages/driver-interface/src/consumers/vehiclePlan.ts, packages/driver-interface/src/services/messaging.ts, packages/driver-interface/src/types.ts
=> feat: show phone number on pickup

packages/engine_umbrella/apps/engine/lib/booking.ex, packages/engine_umbrella/apps/engine/lib/vehicle.ex, packages/engine_umbrella/apps/engine/test/booking_test.exs, packages/engine_umbrella/apps/engine/test/vehicle_test.exs
they need to include lat/lon and be numbers
=> feat: 🎸 validate vehicle/booking addresses

packages/engine-ui/src/components/CreateVehicle.js, packages/engine-ui/src/components/forms/CreateVehicle.js, packages/engine_umbrella/apps/engine/lib/vehicle.ex
allow 1 digit in the fractional part of the volume
=> refactor: 💡 allow float vehicle volume

packages/engine-server/lib/routes.js, packages/engine-ui/src/components/CreateTransport.tsx, packages/engine-ui/src/components/Notifications.tsx, packages/engine-ui/src/components/PlanBookingDetails.tsx, packages/engine-ui/src/components/PlanRouteDetails.tsx, packages/engine-ui/src/components/TransportDetails.tsx, packages/engine-ui/src/components/TransportsList.tsx, packages/engine-ui/src/components/forms/CreateTransport.tsx, packages/engine-ui/src/components/forms/inputs/Checkbox.tsx, packages/engine-ui/src/types.ts
Based on https://github.com/Iteam1337/predictivemovement/pull/265
=> feat: show profile when available

packages/engine-ui/src/components/Map.js, packages/engine-ui/src/utils/mapUtils.js
Add a new map style to the ui.
=> feat: mapbox style

packages/engine_umbrella/apps/engine/lib/adapters/rabbitMQ_rpc_worker.ex, packages/engine_umbrella/apps/engine/lib/plan.ex
Allows for RPC calls to be a little bit slower than 5 seconds.
=> chore: set rpc timeout

README.md, docker-compose.yml, packages/engine_umbrella/apps/engine/lib/booking.ex, packages/engine_umbrella/apps/engine/lib/vehicle.ex, packages/engine_umbrella/apps/engine/test/booking_processor_test.exs
The PR adds pattern matching to the booking / vehicle functions. To make the interfaces better and to be able to catch error's early.
It also fixes a test which previously failed if you're running it after 18.00.
=> chore: more pattern matching

README.md, docker-compose.yml
https://trello.com/c/0ZzbqKjK/388-readme-and-docker-compose-lacks-info-about-postnord-api-token
Use POSTNORD_KEY from env in compose file so that compose can build an image with postnord support
=> Use POSTNORD_KEY from env in compose file

packages/engine-ui/src/components/BookingDetails.js
User can see events that has not yet happened on a booking
=> feat: list expected events in booking detail view

packages/engine-ui/src/components/forms/inputs/AddressSearchInput.js
Check for county when saving favorite address
=> fix: check for county when saving favorite address

k8s/pelias/config.yaml
see https://github.com/pelias/whosonfirst/pull/503
=> fix: 🐛 remove deprecated property

k8s/pelias/config.yaml, k8s/pelias/csv-importer.yaml, k8s/pelias/pip.yaml
- force csv importer to k8s node
- download only Sweden whosonfirst data ( stop being a Pepega and download 33 GB a data)
=> fix: pelias improvements

packages/engine-ui/src/components/CreateBooking.js, packages/engine-ui/src/components/forms/CreateBooking.js
=> feat: add field customer when creating a booking

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/CreateTransport.tsx, packages/engine-ui/src/components/Transports.tsx, packages/engine-ui/src/components/TransportsList.tsx, packages/engine-ui/src/components/forms/CreateTransport.tsx, packages/engine-ui/src/shared-elements/layout.ts
=> Chore: list transport by fleet

packages/driver-interface/src/services/bot.ts
it needs data:image/png annotation
=> fix: 🐛 base64 photo signature

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/shared-elements/links.ts
hover effect for buttons in bookingList
=> styling: hover effect for buttons in bookingList

packages/engine-server/lib/receipts.js, packages/engine-server/lib/routes.js, packages/engine-ui/src/utils/state/reducers/state.ts
Get new signatures without having to refresh the page.
=> fix: get signature

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/TransportDetails.tsx, packages/engine-ui/src/components/TransportsList.tsx, packages/engine-ui/src/shared-elements/links.ts, packages/engine-ui/src/utils/helpers.ts
Focus map on click and move function to helpers.ts
=> Chore: move map to transport

packages/engine-ui/src/components/CreateBooking.js, packages/engine-ui/src/components/Map.tsx, packages/engine-ui/src/components/ServerStatusBar.tsx, packages/engine-ui/src/components/forms/CreateBooking.js, packages/engine-ui/src/components/forms/inputs/AddressSearchInput.js, packages/engine-ui/src/shared-elements/buttons.ts, packages/engine-ui/src/types/state.ts, packages/engine-ui/src/utils/helpers.ts, packages/engine-ui/src/utils/state/stores.ts
**How to test**
Share location button
- Close share location question (not block) and add a booking. You should see a button saying `Dela din nuvarande position` and click it. Allow sharing your position and then the button should disappear and the field should autofill to your current position.  
Share location filled
- Share your location and start add a booking, the `Upphämtning` field should now be filled with your current position. 
Also: Updated colors for the buttons and added a `"neutral"` button.
=> chore: autofill pickup

packages/engine-server/lib/helpers.js
show name instead of id in transport notification
=> chore: show name in notification

packages/engine-ui/src/components/forms/CreateBooking.tsx, packages/engine-ui/src/components/forms/CreateTransport.tsx, packages/engine-ui/src/components/forms/inputs/DateInput.tsx, packages/engine-ui/src/components/forms/inputs/FleetInput.tsx, packages/engine-ui/src/components/forms/inputs/TransportCapacity.tsx
small changes to improve booking form 
* Change ''lämnas'' to ''hämtas''
* Add id to input fields  
* Include ''kontakt'' to ''Avsändare'' and ''Mottagare''
* Switch placement name/contact
* Rename ''nästa'' to ''lägg till mottagare''
=> chore: booking form fixes

packages/driver-interface/src/botRoutes.ts, packages/driver-interface/src/services/messaging.ts
Submitting signature sets package status to delivered
Removed ''Klar'' button
=> submitting signature sets delivery to delivered

packages/driver-interface/src/botRoutes.ts, packages/driver-interface/src/services/bot.ts, packages/driver-interface/src/services/messaging.ts
Remove the second ''Signera'' button from telegram, the first button now leads to the signature window
The signature is now only one click away!!
=> chore: remove the second signature button

packages/signing-ui/src/components/Form.tsx
changed styling on 'Rensa' button
only clear canvas on click instead of both canvas and input field
=> styling: update styling on clear button

packages/booking-interface/adapters/amqp.js, packages/booking-interface/consumers/bookingCreated.js, packages/booking-interface/consumers/index.js, packages/booking-interface/services/index.js, packages/booking-interface/services/messaging.js, packages/booking-interface/wizards/freightslip/handlers.js, packages/booking-interface/wizards/freightslip/messaging.js
* Booking gets added to admin ui from booking bot
* Open added booking in admin ui from booking bot
=> Chore: add booking from booking bot & open added booking in admin ui

packages/engine-ui/src/components/Bookings.tsx, packages/engine-ui/src/components/CreateBooking.tsx, packages/engine-ui/src/components/Map.tsx, packages/engine-ui/src/components/Sidebar.tsx, packages/engine-ui/src/components/SuccessScreen.tsx, packages/engine-ui/src/components/forms/CreateBooking.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/Delivery.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/Pickup.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/Submit.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/WizardForm.tsx, packages/engine-ui/src/components/forms/CreateTransport.tsx, packages/engine-ui/src/components/layout/MainRouteLayout.tsx, packages/engine-ui/src/shared-elements/layout.ts
How to test: 
Create a booking on a smaller (mobile) device.
=> Feat: mobile create booking

packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/routes.js
Problem: We didn't send back the earliest_start and latest_end in the right format to the ui.
=> Fix: save time window booking

packages/engine-ui/src/index.css, packages/signing-ui/src/components/SignParcel.tsx, packages/signing-ui/src/index.css
https://trello.com/c/erIsaafx/568-size-on-canvas-seems-a-bit-off
=> fix: size on canvas

packages/engine-ui/src/components/forms/CreateBooking.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/Delivery.tsx, packages/engine-ui/src/components/forms/CreateBookingWizard/Pickup.tsx
https://trello.com/c/tgFmrDFp/571-admin-ui-fixes
=> fixes: admin UI

packages/engine-ui/src/components/BookingDetails.tsx, packages/engine-ui/src/components/CreateBooking.tsx, packages/engine-ui/src/components/forms/CreateBooking.tsx, packages/engine-ui/src/components/forms/CreateTransport.tsx
* share current location when adding a transport
* add loading feedback when sharing current location
=> chore: share current location when adding a transport

packages/engine-ui/src/components/Bookings.tsx
added ui for booking with status delivery_failed
=> chore: ui for booking with status delivery_failed

packages/api/package-lock.json, packages/api/package.json, packages/api/src/index.ts
Basic stuff.
https://trello.com/c/nsOeOVpw/604-add-logger
```
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/index.ts`
api listening at http://localhost:8000
::ffff:127.0.0.1 - - [25/May/2021:12:07:23 +0000] "GET /transports HTTP/1.1" 200 275 "-" "Dredd/14.0.0 (Darwin 20.3.0; arm64)"
::ffff:127.0.0.1 - - [25/May/2021:12:07:23 +0000] "GET /itinerary/pmv-2314 HTTP/1.1" 200 149 "-" "Dredd/14.0.0 (Darwin 20.3.0; arm64)"
::ffff:127.0.0.1 - - [25/May/2021:12:08:40 +0000] "GET /transports HTTP/1.1" 200 275 "-" "Dredd/14.0.0 (Darwin 20.3.0; arm64)"
::ffff:127.0.0.1 - - [25/May/2021:12:08:40 +0000] "GET /itinerary/pmv-2314 HTTP/1.1" 200 149 "-" "Dredd/14.0.0 (Darwin 20.3.0; arm64)"
```
=> chore: Add morgan logger
