Iteam1337/predictivemovement

packages/engine-elixir/lib/bookingRequests.ex, packages/engine-elixir/lib/dispatch.ex, packages/engine-elixir/lib/engine.ex, packages/engine-elixir/lib/mq.ex, packages/engine-elixir/lib/routes.ex, packages/engine-elixir/test/dispatch_test.exs, skaffold.yaml
- change Routes and BookingRequests from Stream to Agent
- Routes and BookingRequests subscribe to rabbitmq and update the data in the agent on new messages
- Engine sets an interval of 60 seconds where it pulls the data from the agents and clears it so that it won't process it again on next run and then sends to dispatch
- switched everything from Stream to Enum in Dispatch since we don't have Streams anymore
- Reverted back to the Flow piece of code in Dispatch for offering the bookings to drivers in parallel (hopefully it works)
- added a timeout of 20 seconds on the rpc call to prevent people not accepting the offers from blocking the application
=> feat: fixed windows for routes and booking requests

docker-compose.yml, packages/booking-dispatcher/Dockerfile, packages/booking-dispatcher/lib/index.js, packages/booking-interface/consumers/bookingAssignments.js, packages/booking-interface/consumers/deliveryConfirmed.js, packages/booking-interface/consumers/pickupConfirmed.js, packages/engine-server/lib/routes.js, packages/engine-ui/src/App.js, packages/engine-ui/src/components/AddVehicle.js, packages/engine-ui/src/index.tsx, packages/engine/lib/dispatcher.ex, packages/engine/lib/vehicle.ex, packages/vehicle-offer/index.js
This makes sure that the interface doesn't crash if it receives a message without a senderId (aka when the booking is autogenerated)
Also removes the need of .env variable in booking dispatcher. Just place the files in /data folder
=> fix: creating both historical and telegram bookings crashes the system

packages/elixir_umbrella/elixir_apps/engine/lib/booking.ex
We were defining one booking for mq.publish, and different one for the genserver.
=> fix: use same booking for genserver and mq publish

packages/driver-interface/adapters/amqp.js, packages/driver-interface/consumers/pickupInstructions.js
To be consistent with the rest of the queues this PR renames pickup_instructions queue to send_pickup_instructions_to_driver.
=> chore: rename pickup instructions queue

packages/elixir_umbrella/elixir_apps/engine/lib/booking.ex
This adds route to a booking when creating it, so that listeners can plot the route on a map.
=> chore: add route to booking in engine

packages/driver-interface/botRoutes.js, packages/elixir_umbrella/elixir_apps/engine/lib/booking.ex, packages/elixir_umbrella/elixir_apps/engine/lib/booking_updates_processor.ex
This makes elixir ack booking updates, and print error message, if booking id not found.
Also doesn't send message if bot doesn't have vehicle in memory.
=> fix: handle status upated when booking id not in engine

packages/elixir_umbrella/elixir_apps/engine/lib/plan.ex, packages/elixir_umbrella/elixir_apps/engine/test/booking_processor_test.exs
after changing from `position` on vehicle to `start_address` and `end_address` there was an issue in jsprit for vehicles that have the start_address and end_address the same so a `Enum.uniq` was used to filter duplicates.
this change created an issue for having the same address on multiple bookings so now removing the Enum.uniq the issue in jsprit seemed to have been fixed by other changes.
=> fix: issue when using same address for deliver/pickup

packages/elixir_umbrella/elixir_apps/engine/lib/amqp.ex, packages/elixir_umbrella/elixir_apps/engine/lib/vehicle.ex
Found a error in the logs indicating that "cancel-ok" message was not handled. 
With this, we simply take the read the message and do nothing.
=> chore: remove rabbit cancel ok error

docker-compose.yml
This fixes a misconfiguration in docker compose, which will not allow services to start.
=> chore: fix docker-compose env vars

packages/engine_umbrella/apps/engine/lib/vehicle.ex
Move publish of registered car when applying state, so that all subscribers gets the message
=> chore: publish new cars when restarting engine

packages/engine-ui/src/components/Notifications.tsx
Only display last four characters of the booking id in the notification in the admin ui.
=> feat: 🎸 shorten booking id in notification

packages/engine_umbrella/apps/engine/lib/json_serializer.ex, packages/engine_umbrella/config/config.exs, packages/engine_umbrella/config/releases.exs
Replaced https://hexdocs.pm/eventstore/event-serialization.html#json-serialization-using-jason
with a custom serializer that doesn't use "to_existing_atom"
=> fix: use new seralizer to not crash on new atoms

README.md, docker-compose.yml, packages/engine_umbrella/mix.exs
This PR adds an alias for migration & running the engine app.
It also removes the persistance of postgres in docker-compose, meaning if you restart your local postgres, the data will be erased.
=> chore: migrate eventstore on start

packages/engine_umbrella/apps/engine/lib/processors/booking_processor.ex, packages/engine_umbrella/apps/engine/test/booking_processor_test.exs, packages/engine_umbrella/apps/message_generator/lib/message_generator.ex
https://trello.com/c/ImTRBfy8/274-include-excluded-bookings-with-reason-in-the-plan-message
- use the `excluded` property from jsprit and include in the plan an `excluded_booking_ids` list of objects containing id and status
- temporary handle the failure from jsprit and convert it to a status (as this should be returned from jsprit in this format)  that the consumers can decode to a human readable message
=>  feat: 🎸 add excluded booking ids in the plan

packages/engine-server/lib/routes.js, packages/engine-ui/src/components/CreateBooking.js, packages/engine-ui/src/components/CreateVehicle.js, packages/engine-ui/src/components/forms/CreateBooking.js, packages/engine-ui/src/components/forms/CreateVehicle.js, packages/engine-ui/src/components/forms/eventHandlers.js, packages/engine-ui/src/shared-elements/form.ts, packages/engine-ui/src/shared-elements/layout.ts
Send new booking/transport payload in the format that engine expects it.
Also removing undefined default values for string and number inputs, as this interferes with how React works. Instead we check and cast to undefined on submit.
=> fix(engine-ui, engine-server): booking payload

k8s/rabbitmq.yaml, packages/booking-interface/consumers/bookingAssignments.js, packages/booking-interface/consumers/deliveryConfirmed.js, packages/booking-interface/consumers/pickupConfirmed.js, packages/booking-interface/services/amqp.js, packages/driver-interface/src/botRoutes.ts, packages/driver-interface/src/consumers/pickupInstructions.ts, packages/driver-interface/src/consumers/vehiclePlan.ts, packages/driver-interface/src/services/amqp.ts, packages/engine-server/lib/engineConnector.js, packages/engine_umbrella/apps/engine/lib/adapters/rabbitMQ.ex, packages/engine_umbrella/apps/engine/lib/adapters/rabbitMQ_rpc_worker.ex, packages/engine_umbrella/apps/engine/lib/processors/admin_processor.ex, packages/engine_umbrella/apps/engine/lib/processors/booking_delete_processor.ex, packages/engine_umbrella/apps/engine/lib/processors/booking_updates_processor.ex, packages/engine_umbrella/apps/engine/lib/processors/vehicle_delete_processor.ex, packages/engine_umbrella/apps/engine/lib/producers/match_producer.ex, packages/engine_umbrella/apps/engine/test/booking_updates_processor_test.exs, packages/engine_umbrella/apps/message_generator/lib/message_generator.ex, packages/route-optimization-jsprit/src/main/java/com/predictivemovement/route/optimization/MQApplication.java
- change rabbitmq to statefulset and configure the data path
- change exchanges and queues to be durable
- publish messages with persistent
Not the easiest to test.
I've tested it on the `predictivemovement-dev` namespace in the k8s cluster and the test was to change from Deployment to a StatefulSet then create a booking while the engine was not running ( so that it doesn't get consumed )
I've restarted the rabbitmq statefulset to see that the queues are still present on restart and the message for the booking was still in the queue
Before running it locally run
```bash
docker-compose stop && \
docker rm $(docker ps -aq --filter="name=predictivemovement_rabbitmq_1") && \
docker-compose build
```
=> feat: durable rabbitmq

packages/driver-interface/src/services/bot.ts, packages/engine-server/lib/helpers.js, packages/engine-server/lib/routes.js, packages/engine-server/package-lock.json, packages/engine-server/package.json, packages/engine-ui/src/components/forms/CreateVehicle.js
It is still needed to fill in a phone number in the UI that starts with `07..` or `+46` 
On the server a new package has been installed to handle formatting for the number. So the number we save and send though the application is ex. `46700 000 000`. 
It seems as the number we get when sharing your number is `467...` so for now I just removed the replacing of the phone number.
=> chore: validate phone number

packages/engine-ui/src/components/Notifications.tsx, packages/engine-ui/src/components/PlanRouteDetails.tsx, packages/engine-ui/src/components/TransportDetails.tsx, packages/engine-ui/src/components/TransportsList.tsx, packages/engine-ui/src/types.ts
If metadata isn't provided, which we aren't currently not enforcing, the UI will crash unless these checks are in place.
=> fix: metadata is optional

packages/driver-interface/src/botRoutes.ts, packages/driver-interface/src/services/bot.ts, packages/driver-interface/src/services/cache.ts, packages/driver-interface/src/services/messaging.ts
This PR lets a user upon delivering a package; send back a photo of the delivery. The photo is saved as a Telegram photo ID in redis. Can later be retreived with
`https://api.telegram.org/bot<botToken>/getFile?file_id=<insert the ID here>`
Which will generate a file_path which can be used like:
`https://api.telegram.org/file/bot<botToken>/<insert file_path here>`
=> feat: driver delivery receipt

packages/engine_umbrella/apps/engine/test/booking_processor_test.exs, packages/engine_umbrella/apps/engine/test/booking_test.exs, packages/engine_umbrella/apps/engine/test/vehicle_test.exs, packages/engine_umbrella/apps/message_generator/lib/adapters/rabbitMQ.ex, packages/engine_umbrella/apps/message_generator/lib/booking_generator.ex, packages/engine_umbrella/apps/message_generator/lib/generator.ex, packages/engine_umbrella/apps/message_generator/lib/message_generator.ex, packages/engine_umbrella/apps/message_generator/lib/message_generator/application.ex, packages/engine_umbrella/apps/message_generator/lib/transport_generator.ex, packages/engine_umbrella/apps/message_generator/mix.exs
This cleans up the message generator and makes it follow the same RMQ pattern as the engine.
the public API is now renamed as 
Generator.add_booking
Generator.add_transport
with the option of inserting a map with props that should not be overwritten
or a atom which sets the city for the transport/booking.
=> chore: clean message generator

docker-compose.yml
https://trello.com/c/A9xdFq0f/375-docker-compose-should-bind-to-localhost-instead-of-global
=> chore: make compose listen to localhost instead of all interfaces

k8s/osrm.yaml
The time-distance-matrix is limited by 100 locations. This will hopefully upgrade the table size, but could also be critical in high memory usage. We need to watch this.
=> feat: set OSRM time-distance-matrix size to 10000

packages/engine-ui/src/utils/IconClusterLayer.js, packages/engine-ui/src/utils/mapUtils.js
Something with this setup sometimes causes alot of flickering in the browser. Disable until we know how to implement properly.
=> fix: disable icon transitions on custom layer

.github/workflows/tests.yml
[actions/setup-elixir](https://github.com/actions/setup-elixir) by Github is no longer maintained. Project is forked as [erlef/setup-elixir](https://github.com/erlef/setup-elixir) and maintained by The Erlang Ecosystem Foundation.
This fixes this error we had:
```
Run actions/setup-elixir@v1.0.0
Installing OTP 23.1
/home/runner/work/_actions/actions/setup-elixir/v1.0.0/src/install-otp-ubuntu 23.1
Reading package lists...
Building dependency tree...
Reading state information...
libwxbase3.0-0v5 is already the newest version (3.0.4+dfsg-15build1).
libwxbase3.0-0v5 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package libwxgtk3.0-0v5 is not available, but is referred …
```
=> fix: replace deprecated actions/setup-elixir with erlef/setup-elixir

packages/engine-ui/src/hooks/useGetSuggestedAddresses.ts, packages/engine-ui/src/utils/helpers.ts
When searching for address we now get the closets matches from where the map is displayed.
=> chore: implement focus point to pelias query

packages/engine-server/lib/engineConnector.js, packages/engine-server/lib/index.js
we should change the limit only for amqp and not set it globally
=> fix: 🐛 event listeners warning

packages/engine-ui/src/SignParcel.tsx
* Remove margin top.
* Add different height to signature box so that it will always be visible, even when tilting the phone.
Tested on several devices in inspector in brave and firefox.
=> make signature box always visible

packages/auto-accept-offer/amqp.js, packages/auto-accept-offer/package-lock.json, packages/booking-dispatcher/lib/adapters/amqp.js, packages/driver-interface/src/adapters/amqp.ts, packages/vehicle-offer/amqp.js
This adds reconnect to rabbitmq that would otherwise just crash the following packages:
- driver-interface
- auto-accept-offer
- vehicle-offer
Scenarios tested:
- rabbitmq is not available on startup of applications but then becomes available ( easier to test by running any of the services below local )
- rabbitmq becomes unavailable for a period of time ( `docker stop` and `docker start`)
---
Have tested both running in Docker or locally, if you run it in Docker make sure to run `docker-compose build` and have `TELEGRAM_BOT_TOKEN` env variable set
Have tested both running in Docker or locally, if you run it in Docker make sure to run `docker-compose build`
=> fix: rabbitmq reconnect 

packages/engine-ui/src/components/Sidebar.tsx
How to test: 
Create a booking/transport in a mobile view and see no notification. 
Create a booking/transport in desktop view and see a notification
=> chore: hide notifications in mobile view

packages/driver-interface/src/services/messaging.ts
Changes: 
Update text in driver-interface to make it clear that we just save one picture.
=> chore: specify that driver-bot just saves one pic

README.md, docker-compose.yml, packages/engine_umbrella/apps/engine/mix_tasks/create_test_database.ex, packages/engine_umbrella/config/config.exs
Make docker compose use files from disk instead of building an image. This way you don't have to build a new image to test changes. You also don't have to export environment variables to get them into the image, instead each service will use its .env-file.
=> Compose use files from disk

packages/engine-ui/src/components/forms/CreateBooking.tsx
The time window was reset when going into edit for a booking with time windows. 
The current position updated from the edit view and by doing that the time windows got removed. 
Just use the current position while creating a booking.
=> fix: just update current position in create not in edit

packages/auto-accept-offer/amqp.js, packages/auto-accept-offer/index.js, packages/vehicle-offer/amqp.js, packages/vehicle-offer/index.js
This fixes an issue with `vehicle-offer` and `auto-accept-offer` packages where even though they reconnect to rabbitmq on error, our code for adding queue listeners doesn't run anymore which causes them to not receive messages and thus causing problems with confirming plan flow.
Made it so that we pass the queues listener setup as a callback to connect function that handles reconnecting and will invoke this setup on reconnect.
First to reproduce the bug you can test it on `master` branch and it sometimes happens when you run `docker-compose up` due to rabbitmq not being ready to accept connections. 
A more reliable method is to comment out one of this packages from the `docker-compose` file and make sure nothing is running in Docker. Then start the service locally and then run …
=> fix: 🐛 reconnect rabbitmq in vehicle-offer & auto-accept-offer

packages/api/src/routeHandlers.ts
While perusing the code base I noticed that we can make use of the generated typescript schema for our request handlers. Just submitting this PR as a proof-of-concept and reference kind of things, and for your opinions of course 😄
=> chore: Use types from spec to specify Request parameters

packages/engine-ui/src/components/CreateTransport.tsx, packages/engine-ui/src/components/EditTransport/EditTransport.tsx, packages/engine-ui/src/components/EditTransport/index.tsx, packages/engine-ui/src/components/TransportDetails.tsx, packages/engine-ui/src/utils/helpers.ts
and display them in local format
Co-authored-by: Izabella Larsson <izabellalarsson@users.noreply.github.com>
It fixes (together with a change in the route-optimization package) an issue where even though the driver schedule should not allow them to be able to pickup and deliver a booking, a route can in some cases still be created and assigned to them.
The issue can be replicated on the `master` branch with the following input data that should not produce a plan (one should try to use fairly close locations so that driving time is not an issue):
```
transport schedule: 8 - 9
booking:
pickup: 9:30 - 13:30
delivery: 10:30 - 11:30
```
This fix will only work in conjunction with a change in the route-optimization package, so make sure [this …
=> feat: send driver dates in UTC

docker-compose.yml
It was accidentally added back in cfcebf3b but we don't use it so it should not run
=> chore: remove extract-text-from-pic from compose again

packages/engine_umbrella/apps/engine/mix_tasks/release_tasks.ex
Fixes this mess:
```
The EventStore schema already exists.
> [engine-7b865b48f7-lhz8x engine-migrations] ** (UndefinedFunctionError) function EventStore.Tasks.Init.exec/3 is undefined or private. Did you mean one of:
> [engine-7b865b48f7-lhz8x engine-migrations]       * exec/1
> [engine-7b865b48f7-lhz8x engine-migrations]       * exec/2
...<HIDDEN CONTENT>...
> [engine-7b865b48f7-lhz8x engine-migrations]     (engine 0.1.0) mix_tasks/release_tasks.ex:10: Engine.ReleaseTasks.init_event_store/0
> [engine-7b865b48f7-lhz8x engine-migrations]     (stdlib 3.14.2) erl_eval.erl:680: :erl_eval.do_apply/6
> [engine-7b865b48f7-lhz8x engine-migrations]     (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
```
=> fix: 🐛 engine k8s init container after elixir upgrade
